### PR TITLE
[WIP]Updated tax tables for South Carolina

### PR DESCRIPTION
**Pull request by cstait**

### CODE REVIEW

**Comment by cstait** [comment]
We may have to redo deductions too... looks like they're suppose to be a flat amount?

**Comment by mattgwagner** [comment]
That's a pretty big change in numbers. Not doubting you, but can you source this info so I can see where I went wrong the first time?

**Comment by cstait** [comment]
@mattgwagner https://dor.sc.gov/forms-site/Forms/SC1040ES_09302015.pdf

Looks like I still got a few of the numbers off, I'll change ASAP.

**Comment by mattgwagner** [comment]
Some of those "estimated tax worksheets" are purely for, well, estimation.

Reference this instead @ https://dor.sc.gov/tax/withholding

**Comment by mattgwagner** [comment]
Also, when you review them, make sure you reference Tax Year 2016. The most obvious ones on that page are for 2017.

https://dor.sc.gov/tax/withholding/forms

**Pull request closed without merging**
