### PR TITLE
Cpo 1910 maryland swt

### PR DESCRIPTION
**Pull request by cstait**
Kind of messy, as far as I could tell there is no "universal" state withholding, just an allowance and standard deduction. I added all the tables for locals, even if you end up doing something else with local taxes you could reuse them.

### CODE REVIEW

**Comment by mattgwagner** [comment]
Missing unit tests for verification?

**Comment by cstait** [comment]
I can go ahead and start adding unit tests but I wasn't sure if that's how you had wanted to handle local taxes (having them reported within the state withholding).

**Comment by mattgwagner** [comment]
I'd need to look at it more closely -- SWT definitely needs to be split out from local withholding/taxes/fees/etc for reporting.

**Comment by mattgwagner** [comment]
Reviewed this a bit more in depth, ended up here @ http://taxes.marylandtaxes.com/Business_Taxes/Business_Tax_Types/Income_Tax/Employer_Withholding/Withholding_Tables/Percentage_Method.shtml

It looks like we'd be safe applying the rates there rather than requiring a table-per-county, as implemented in this pull request. It "either matches or closely approximates" without going below.

**Pull request closed without merging**
